### ISSUE TITLE
Yeet among us easter egg

### ISSUE THREAD

**Issue by B1ueJie** [coravacav/uofu-cs-discord-bot#73]
1/1000 chance for an emergency meeting to occur instead of usual yeet
- when the emergency meeting occurs the following happens:
1. a gif is played first to signify the new event
2. the gif disappears and is replaced with a new dialogue

"Is [insert name here] the impostor?"
(potentially adding the user's pfp would be fun)

3. afterwards another gif is played displaying that the user was either voted out or that they weren't voted out
(following gifs are placeholders, i'll have to grab some material for a smoother experience)
https://tenor.com/view/emergency-meeting-among-us-meeting-discuss-gif-18383222
https://tenor.com/view/among-us-ejected-impostor-gif-19787031
https://cdn.discordapp.com/attachments/1065374082373271655/1286171602525880350/No_one_was_ejected.gif?ex=66ecf025&is=66eb9ea5&hm=ea740fe207b75c6c27852bae83e9724377cfe08d5f523653bf0c6b3cf82b7232&

**Comment by coravacav** [comment]
Done!
