### ISSUE TITLE
Kingfisher react for "holiday"

### ISSUE THREAD

**Issue by RohanVittalMV** [coravacav/uofu-cs-discord-bot#90]
Holidays are just an excuse people use to justify procrastination. But if you’re serious about achieving your goals, you need to approach life with the same mindset Kobe had. It’s not about skipping Thanksgiving forever—it’s about using the time you have wisely. That hour spent solving a few Leetcode problems is one step closer to the life you’ve been working toward.

Your family will still be there when you’ve made it. In fact, they’ll be even prouder of you when you land that six-figure offer or that prestigious internship. Success isn’t about making excuses; it’s about staying consistent, even when the world says to take a break.

**Comment by RohanVittalMV** [comment]
https://www.reddit.com/r/csMajors/comments/1h21v04/happy_thanksgiving_but_you_should_be_leetcoding/

**Comment by coravacav** [comment]
Done!
